name: decision dice

on:
  push:
    branches: [ main ]

jobs:
  cluster:
    name: Deploy decision dice frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      id: credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: |
        npm run build
    - name: Sync with S3
      run: |
        aws s3 sync ./out s3://decision-dice-motivators